version: '2'
services:
  freshing-admin:
    image: renren/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  freshing-api:
    image: renren/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev